healthcheck:
  version : version 1 . 0


server:
  port: 8082


spring:
 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examen-clinique?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Ilyas.00
    hikari:
      initialization-fail-timeout: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/

  instance:
    hostname: localhost

